corona-dash:
  database-connection-string: mongodb+srv://springer:springer@cluster0.4t2hp.mongodb.net/svlit?retryWrites=true&w=majority
  refresh-delay-ms: ${CD_REFRESH_DELAY_MS:3600000}
  server-port: ${CD_SERVER_PORT:8080}
  source-url: ${CD_SOURCE_URL}

home:
  telegram-name: Telegram
  telegram-icon-url: /static/img/ic_telegram.svg
  telegram-base-url: https://t.me/
  telegram-user-identifier: svlitvinenko
  telegram-visible-name: Sergei Litvinenko
  quotes-api-base-url: https://quotes.rest/qod
  email-user-identifier: sv.litvinenko@outlook.com
  email-icon-url: /static/img/ic_email.svg

server:
  port: ${corona-dash.server-port}

spring:
  datasource:
    url: jdbc:postgresql://localhost/sweater
    username: springapp
    password: QqSpring
  jpa:
    generate-ddl: true
