corona-dash:
  database-protocol: ${CD_DATABASE_PROTOCOL}
  database-host: ${CD_DATABASE_HOST}
  database-user: ${CD_DATABASE_USER}
  database-password: ${CD_DATABASE_PASSWORD}
  database-name: ${CD_DATABASE_NAME}
  refresh-delay-ms: ${CD_REFRESH_DELAY_MS:3600000}
  server-port: ${CD_SERVER_PORT:8080}
  source-url: ${CD_SOURCE_URL}

home:
  telegram-name: Telegram
  telegram-icon-url: /img/ic_telegram.svg
  telegram-base-url: https://t.me/
  telegram-user-identifier: svlitvinenko
  telegram-visible-name: Sergei Litvinenko
  quotes-api-base-url: https://quotes.rest/qod
  email-user-identifier: sv.litvinenko@outlook.com
  email-icon-url: /img/ic_email.svg

server:
  port: ${corona-dash.server-port}
