corona-dash:
  refresh-delay-ms: ${CD_REFRESH_DELAY_MS:3600000}
  server-port: ${CD_SERVER_PORT:8080}
  source-url: ${CD_SOURCE_URL}

global:
  database-connection-string: ${SVLIT_DB_PATH}
  base-url: ${SVLIT_BASE_URL:http://localhost:8080}

home:
  telegram-name: Telegram
  telegram-icon-url: /static/img/ic_telegram.svg
  telegram-base-url: https://t.me/
  telegram-user-identifier: svlitvinenko
  telegram-visible-name: Sergei Litvinenko
  quotes-api-base-url: https://quotes.rest/qod
  email-user-identifier: sv.litvinenko@outlook.com
  email-icon-url: /static/img/ic_email.svg

server:
  port: ${corona-dash.server-port}
  jpa:
    generate-ddl: true

authentication:
  mail:
    host: smtp.yandex.ru
    username: robot@svlit.ru
    password: jZWJ8arfmiCY9rX
    port: 465
    protocol: smtps
    debug: true