corona-dash:
  database-protocol: ${CD_DATABASE_PROTOCOL}
  database-host: ${CD_DATABASE_HOST}
  database-user: ${CD_DATABASE_USER}
  database-password: ${CD_DATABASE_PASSWORD}
  database-name: ${CD_DATABASE_NAME}
  refresh-delay-ms: ${CD_REFRESH_DELAY_MS:3600000}
  server-port: ${CD_SERVER_PORT:8080}
  source-url: ${CD_SOURCE_URL}

server:
  port: ${corona-dash.server-port}
